### PR TITLE
Add support for text alignment and improve a little bit source code formatting

### PR DESCRIPTION
**Pull request by PhenX**
It may also improve a little bit performance

### CODE REVIEW

**Comment by Anastaszor** [comment]
Thank you. I have 2 questions about this commit.

Is the ```strpos("-alphabet-")``` really faster than the ```ord()``` implementation in the parser ?

What do you think of the ```if($group instanceof Thing)``` list in the `formatGroup` method ? The same is true for the `formatControlWord` method ?

Anyway i have no reason not to merge.

You said you've integrated this lib in your project. I must say, even if i think you're well aware of it, that this lib is still incomplete and not a version 1.0.0, so backward compatibility is not guaranteed. I think at this time that two things must be done before 1.0.0 : first is harmonization of method names, and second is usage of polymorphism among classes.

**Comment by PhenX** [comment]
Hi @Anastaszor ,
I have to admit I didn't really bench for the `strpos()` vs `ord()`, but I'll do it and tell you. I even think I found a better way than both of them.

About the `if($group instanceof Thing)` list in the `formatGroup` method, I'm not really fond of it ... 
I think it would be better with a class for every Group type, in a special namespace (that is also a subject I'd like to talk with you).
Something like that :

* `\Rtf`
  * `\Parser`
  * `\ControlWord`
  * ...
  * `\Group`
    * `\Group`
    * `\Generic`
    * `\FontTable`
    * `\ColorTable`
    * ...
  * `\Output`
    * `\Html`
      * `ControlWord`
      * `ControlText`
      * ..
    * `\Rtf`
      * `ControlWord`
      * `ControlText`
      * ..

And about the stability of the project, I'm totally aware of it, no worries, we include a specific version, not the master itself, and when there are release, we'll integrate them.

**Comment by Anastaszor** [comment]
Hi @PhenX 
I'm interested in the benchs. I'm also interested to see the third way. :)

I agree for most of the structure you proposed (I do not feel the need for different ControlWord classes in output for example, for me its a Group like the others, but I may be wrong). I totally agree with the fact that the more class we have, the more flexibility can be given to the lib, and the fact that every group should have their own class. The structure of the folders can be changed if needed, the only thing to take care of is the merging if we do concurrent moves.

I'm not fond of namespaces for now, but i think this is a subject outside of the scope of this PR.

**Comment by PhenX** [comment]
Well, my version was the worst :)
 * The original : 343.581 ms
 * Mine : 416.392 ms
 * The new one : 135.081 ms

The new one is : 
```php
    $char = $this->char;
    return $char >= 'A' && $char <= 'Z' || $char >= 'a' && $char <= 'z';
```

No function call ! It also works for the isDigit method.

**Comment by Anastaszor** [comment]
Inplicit conversions is the best. Interesting.

This is tricky, and this only works without parenthesis because we assumed ASCII text ; in which the range [a-z] is >= to A. 
For faster implementations we should do statistical analysis of the rtf files. If proven that lowercase characters are more used, it may be reversed in 
```php
return $char <= 'z' && $char >= 'a' || $char <= 'Z' && $char >= 'A';
```

**Pull request merged**
